# 非アクティブなペインのスタイル（背景を少しグレーにするなど）
set -g window-style 'fg=colour247,bg=colour238'

# アクティブなペインのスタイル（背景を黒にするなど）
set -g window-active-style 'fg=terminal,bg=terminal'

# ペインの境界線の色も調整するとより見やすくなります
set -g pane-border-style 'fg=colour238,bg=colour235'
set -g pane-active-border-style 'fg=colour51,bg=colour236'

# ペインボーダーの表示を有効にする
set -g pane-border-status bottom

# ボーダーに表示する内容（現在のパス：#{pane_current_path}）
set -g pane-border-format "#[fg=black,bg=cyan] #P: #{pane_current_path} "

#マウス操作を有効にする
set-option -g mouse on

# スクロールアップするとコピーモードに入る
bind-key -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'select-pane -t=; copy-mode -e; send-keys -M'"

# 最後までスクロールダウンするとコピーモードを抜ける
bind-key -n WheelDownPane select-pane -t= \; send-keys -M

# コピーモードでvimキーバインドを使う
setw -g mode-keys vi

# コピーモード中に Vim 風に v で選択範囲を定める
bind -Tcopy-mode-vi v send -X begin-selection

# コピーモード中に Vim 風に y で選択範囲をヤンクしてコピーモードを終了する
bind -T copy-mode-vi y send -X copy-selection-and-cancel

# マウスをドラッグして選択範囲を定め、それをヤンクしてコピーモードを終了する
bind -T copy-mode-vi MouseDragEnd1Pane send -X copy-selection-and-cancel

# コピーしたテキストをクリップボードに保存
set -g set-clipboard on
