[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'stephpy/vim-yaml'
on_ft = ['yaml']

[[plugins]]
repo = 'udalov/kotlin-vim'
on_ft = ['kotlin']

[[plugins]]
repo = 'keith/swift.vim'
on_ft = ['swift']

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_source = 'denite.nvim'
on_event = 'TextYankPost'

[[plugins]]                                    
repo = 'iamcco/markdown-preview.nvim'
on_ft = ['markdown', 'md']
build = 'sh -c "cd app && yarn install"'

[[plugins]]                                    
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown', 'md']
